frameworkVersion: '>=2.5.0 <2.6.0'

plugins:
  - serverless-stack-termination-protection
  - serverless-pseudo-parameters
  - serverless-dotenv-plugin

service: cloudwatch2rollbar

provider:
  name: aws
  runtime: java11
  memorySize: 1024
  stage: ${env:STAGE}
  region: ${opt:region, 'eu-west-2'}
  timeout: 30
  versionFunctions: false
    
package:
  individually: true
  excludeDevDependencies: true

functions:
  cloudwatch2rollbar:
    handler: com.alanguerin.Handler
    package:
      artifact: function-cloudwatch2rollbar/build/distributions/function-cloudwatch2rollbar.zip
    events:
      - cloudwatchLog: '/aws/lambda/bloomboxclub-floraathome-fulfillment-test-fetch-stock'
      